/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f103x6.h"
#include "STM32_F103C6_GPIO.h"
#include "STM32_F103C6_EXTI_Driver.h"
#include "lcd.h"



enum CPU_access_level{
	privileged,
	unprivileged
};

void switch_access_level(enum CPU_access_level level){

	switch(level){
	case unprivileged:
			//Set bit 0(Priv) in Control reg
		__asm("mrs r2, CONTROL \n\t"
			  "orr r2,r2,#0x1  \n\t"
			  "msr CONTROL,r2  \n\t"
				);
		break;
	case privileged:
		//Clear bit 0(Priv) in Control reg
	__asm("mrs r2, CONTROL \n\t"
		  "lsr r2,r2,#0x1  \n\t"
		  "lsl r2,r2,#0x1  \n\t"
		  "msr CONTROL,r2  \n\t"
			);
	break;

	}
}

void clock_init()
{
	RCC_GPIOA_CLK_EN();// IO port A clock enable
	RCC_GPIOB_CLK_EN(); // IO port B clock enable
}

unsigned IRQ_flag=0;
void EXTI9_CallBack(void){
	IRQ_flag=1;


}

int main(void)
{

	RCC_GPIOA_CLK_EN();// IO port A clock enable
	RCC_GPIOB_CLK_EN(); // IO port B clock enable

	RCC_AFIO_CLK_EN();

	EXTI_PinConfig_t EXTI_CFG;
	EXTI_CFG.EXTI_PIN= EXTI9PB9;
	EXTI_CFG.Trigger_Case= EXTI_TRIGGER_RISING;
	EXTI_CFG.P_IRQ_Callback= EXTI9_CallBack;
	EXTI_CFG.IRQ_EN= EXTI_IRQ_Enable;
	MCAL_EXTI_GPIO_INIT(&EXTI_CFG);

	switch_access_level(unprivileged);


	//clock_init();

	IRQ_flag=1;
	while(1){
		if(IRQ_flag){
			IRQ_flag=0;
		}

	}


}
