/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f103x6.h"
#include "STM32_F103C6_GPIO.h"
#include "STM32_F103C6_EXTI_Driver.h"
#include "lcd.h"

int read_IPSR;
int read_CTRL=10;


void clock_init()
{
	RCC_GPIOA_CLK_EN();// IO port A clock enable
	RCC_GPIOB_CLK_EN(); // IO port B clock enable
}
void GPIO_init()
{

	GPIO_Pin_Config_t PinCfg;
	//PA1 input HIGH Z
	PinCfg.GPIO_PinNumber= GPIO_PIN_1;
	PinCfg.GPIO_MODE= GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_INIT(GPIOA, &PinCfg);

	//PB1 output push pull mode
	PinCfg.GPIO_PinNumber= GPIO_PIN_1;
	PinCfg.GPIO_MODE= GPIO_MODE_OUTPUT_PP;
	PinCfg.GPIO_OUTPUT_Speed= GPIO_SPEED_10M;
	MCAL_GPIO_INIT(GPIOB, &PinCfg);

	//PA13 input HIGH Z
	PinCfg.GPIO_PinNumber= GPIO_PIN_13;
	PinCfg.GPIO_MODE= GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_INIT(GPIOA, &PinCfg);



	//PB13 output push pull mode
	PinCfg.GPIO_PinNumber= GPIO_PIN_13;
	PinCfg.GPIO_MODE= GPIO_MODE_OUTPUT_PP;
	PinCfg.GPIO_OUTPUT_Speed= GPIO_SPEED_10M;
	MCAL_GPIO_INIT(GPIOB, &PinCfg);
}
void wait(int x){
	unsigned int i,j;
	for(i=0;i<x;i++){
		for(j=0;j<255;j++);
	}
}

unsigned IRQ_flag=0;
void EXTI9_CallBack(void){
	IRQ_flag=1;
	__asm("MRS %0, IPSR"
			:"=r" (read_IPSR));

}

int main(void)
{
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
	RCC_AFIO_CLK_EN();



	EXTI_PinConfig_t EXTI_CFG;
	EXTI_CFG.EXTI_PIN= EXTI9PB9;
	EXTI_CFG.Trigger_Case= EXTI_TRIGGER_RISING;
	EXTI_CFG.P_IRQ_Callback= EXTI9_CallBack;
	EXTI_CFG.IRQ_EN= EXTI_IRQ_Enable;
	MCAL_EXTI_GPIO_INIT(&EXTI_CFG);
	__asm("MRS %0, CONTROL"
				:"=r" (read_CTRL));


	clock_init();

	IRQ_flag=1;
	while(1){
		if(IRQ_flag){
			IRQ_flag=0;
		}

	}


}
